analyzer:
  errors:
    unused_local_variable: ignore
  exclude:
    - packages/tfchain_client/lib/generated/**
    - packages/tfchain_client/pubspec.yaml
    - pubspec.yaml
    - packages/graphql_client/bin/graphql_client.dart
