name: tfgrid_sdk_dart_monorepo
packages:
  - packages/**

scripts:
  analyze:
    run: melos exec -- flutter analyze .
    description: Run `dart analyze` in all packages (linting).
  unit_test:
    run: |
      EXCLUDE_PACKAGE="stellar_client"

      export PATH="$PATH:/opt/hostedtoolcache/flutter/stable-3.16.0-x64/bin"

      for package in $(ls packages); do
        if [ "$package" != "$EXCLUDE_PACKAGE" ]; then
          echo "Running tests in $package"
          cd "packages/$package"
          flutter test --no-pub --coverage
          cd ../..
        else
          echo "Skipping $package"
        fi
      done
    description: Run all Flutter tests in this project.
  unit_test_and_coverage:
    description: Merge all packages coverage trace files ignoring data related to generated files.
    run: |
      melos exec rm -rf coverage
      melos run unit_test
      melos exec -c 1 --file-exists=coverage/lcov.info -- coverde filter --input ./coverage/lcov.info --output MELOS_ROOT_PATH/coverage/filtered.lcov.info --filters \.g\.dart
      coverde value -i coverage/filtered.lcov.info > MELOS_ROOT_PATH/coverage/result.txt
