name: tfgrid_sdk_dart_monorepo
packages:
  - packages/**

scripts:
  analyze:
    run: melos exec -- flutter analyze .
    description: Run `dart analyze` in all packages.
  unit_test:
    run: melos exec --dir-exists="test" --fail-fast -- flutter test --no-pub --coverage
    description: Run all Flutter tests in this project.
  unit_test_and_coverage:
    description: Merge all packages coverage tracefiles ignoring data related to generated files.
    run: |
      melos exec rm -rf coverage
      melos run unit_test
      melos exec bash -c 'cd $(pwd) && dart pub global run coverde filter --input coverage/lcov.info --output coverage/filtered.lcov.info --filters .g.dart'
      melos exec bash -c 'cd $(pwd) && dart pub global run coverde value -i coverage/filtered.lcov.info > coverage/result.txt'