name: tfgrid_sdk_dart
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

dependencies:
  coverage: ^1.7.1
  melos: ^3.2.0
  signer:
    path: ./packages/signer
  tfchain_client:
    path: ./packages/tfchain_client
  rmb_client:
    path: ./packages/rmb_client
