name: tfgrid_sdk_dart
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.3.1

dev_dependencies:
  coverage: ^1.6.3
  lints: ^3.0.0
  test: ^1.24.0
dependencies:
  melos: ^3.2.0
