name: rmb_client
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  fixnum: ^1.1.0
  polkadart_keyring: ^0.4.3
  protobuf: ^3.1.0
  web_socket_channel: ^2.4.1
  tfchain_client:
    path: ../tfchain_client

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
