name: stellar_client
description: A sample command-line application.
version: 0.1.0

environment:
  sdk: ^3.2.3

dependencies:
  http: ^1.2.0
  reflectable: '>=4.0.6 <4.0.9'

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
