name: stellar_client
description: A sample command-line application.
version: 0.1.0

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  http: 1.2.0
  stellar_flutter_sdk: ^1.7.5

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

