name: Analyze

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Repository
        uses: actions/checkout@v2

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1.6.0
        with:
          sdk: "3.2.0"
      - name: Install Melos
        run: dart pub global activate melos

      - name: Install Dart dependencies
        run: |
          melos exec -c 1 -- \
            'if [ "$MELOS_PACKAGE_NAME" != "stellar_client" ]; then dart pub get; fi'

      - name: Install Flutter dependencies
        run: |
          melos exec -c 1 -- \
            'if [ "$MELOS_PACKAGE_NAME" == "stellar_client" ]; then flutter pub get; fi'

      - name: Analyze Dart packages
        run: |
          melos exec -c 1 -- \
            'if [ "$MELOS_PACKAGE_NAME" != "stellar_client" ]; then dart analyze .; fi'

      - name: Analyze Flutter packages
        run: |
          melos exec -c 1 -- \
            'if [ "$MELOS_PACKAGE_NAME" == "stellar_client" ]; then flutter analyze .; fi'
