name: Coverage

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Repository
        uses: actions/checkout@v2

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1.6.0
        with:
            sdk: 'stable'

      - name: Install Melos
        run: dart pub global activate melos      

      - name: Install dependencies
        run: dart pub global run melos bootstrap

      - name: Analyze
        run: dart analyze .

      - name: Test and Coverage
        run: |
          melos exec rm -rf coverage
          melos exec --dir-exists="test" --fail-fast -- flutter test --no-pub --coverage
          melos exec dart pub global run coverde filter --input ./coverage/lcov.info --output ./coverage/filtered.lcov.info --filters .g.dart
          melos exec dart pub global run coverde value -i ./coverage/filtered.lcov.info > ./coverage/result.txt

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
