name: Build and Test

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Repository
        uses: actions/checkout@v2

      - name: List Files
        run: ls -R

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1.6.0
        with:
          sdk: 'stable'

      - name: Install Melos
        run: dart pub global activate melos      

      - name: Install dependencies
        run: melos bootstrap

      - name: Run unit tests
        run: melos run unit_test

      - name: Merge coverage
        run: melos run unit_test_and_coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
