
name: tfgrid-sdk-dart Workflow

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Dart
        uses: dart-lang/setup-dart
        with:
          sdk: "stable"

      - name: Install Melos
        run: dart pub global activate melos

      - name: Bootstrap Melos
        run: dart pub global run melos bootstrap

      - name: Run Tests
        run: dart pub global run melos run test
